/**
 * Pure parsing of the Gmail REST API's `Message`/`MessagePart` shape
 * (verified against https://developers.google.com/gmail/api/reference/rest/v1/users.messages)
 * — split out from `GmailConnectorService` so it's unit-testable without
 * mocking `fetch`, the same reasoning as `buildDonutArcs`/`sortItems`
 * elsewhere in this project (packages/ui has no DOM to test against;
 * here there's no network to mock against).
 */
export interface GmailHeader {
  name: string;
  value: string;
}

export interface GmailMessagePart {
  mimeType?: string;
  filename?: string;
  headers?: GmailHeader[];
  body?: { data?: string; attachmentId?: string; size?: number };
  parts?: GmailMessagePart[];
}

export interface GmailMessage {
  id: string;
  /** Gmail's conversation id (Message resource `threadId`). */
  threadId?: string;
  /** e.g. INBOX, SENT, DRAFT, SPAM — used for deterministic direction hints. */
  labelIds?: string[];
  payload?: GmailMessagePart;
  /** Epoch milliseconds, as a string (Gmail's int64 JSON convention). */
  internalDate?: string;
}

export interface ParsedGmailHeaders {
  from: string;
  to: string[];
  subject: string;
  receivedAt: Date;
  /** RFC 5322 `Message-ID`, `In-Reply-To` and `References` — the strong correlation keys (Amendment 02 §13.1). */
  rfcMessageId?: string;
  inReplyTo?: string;
  references: string[];
  /** Deterministic technical hints (never a business decision): auto-responder, bulk/list mail. */
  autoGenerated: boolean;
  bulk: boolean;
}

export interface GmailAttachmentRef {
  filename: string;
  mimeType: string;
  attachmentId: string;
}

function decodeBase64Url(data: string): string {
  const normalized = data.replace(/-/g, '+').replace(/_/g, '/');
  return Buffer.from(normalized, 'base64').toString('utf8');
}

/** Gmail's attachment `data` field is already base64url — this project's `EmailAttachment.contentBase64` expects standard base64, so re-pad/translate rather than decode-then-reencode (keeps binary attachments binary-safe). */
export function base64UrlToBase64(data: string): string {
  return data.replace(/-/g, '+').replace(/_/g, '/');
}

function getHeader(headers: GmailHeader[] | undefined, name: string): string {
  return headers?.find((h) => h.name.toLowerCase() === name.toLowerCase())?.value ?? '';
}

/**
 * RFC 5322 `From`/`To` header values are commonly `"Display Name" <addr@example.com>`,
 * not a bare address — Gmail returns the header exactly as received, unparsed.
 * Every consumer downstream (`IntakeService.runSalesAgent()`'s `fromAddress.split('@')`
 * domain/local-part derivation, the `create_contact`/`find_contact` tools' `z.string().email()`
 * validation, `IncomingEmailDto`'s own `@IsEmail()` convention for the simulated path) already
 * assumes a bare address — found live against a real connected Gmail account
 * (docs/ASSUMPTIONS.md Channel Event Runtime Increment D): a real message with a display-name
 * `From` header made the Sales agent's `create_contact` tool call fail Zod validation silently
 * (empty `AgentRun.errorMessage` — the underlying cause, not this function, but what exposed it).
 */
function extractEmailAddress(rawHeaderValue: string): string {
  const angleMatch = rawHeaderValue.match(/<([^<>]+)>\s*$/);
  return (angleMatch?.[1] ?? rawHeaderValue).trim();
}

function findPlainTextPart(part: GmailMessagePart | undefined): GmailMessagePart | undefined {
  if (!part) return undefined;
  if (part.mimeType === 'text/plain' && part.body?.data) return part;
  for (const child of part.parts ?? []) {
    const found = findPlainTextPart(child);
    if (found) return found;
  }
  return undefined;
}

function collectAttachmentParts(part: GmailMessagePart | undefined): GmailMessagePart[] {
  if (!part) return [];
  const result: GmailMessagePart[] = part.filename && part.body?.attachmentId ? [part] : [];
  for (const child of part.parts ?? []) {
    result.push(...collectAttachmentParts(child));
  }
  return result;
}

export function parseGmailMessageHeaders(message: GmailMessage): ParsedGmailHeaders {
  const headers = message.payload?.headers;
  const toRaw = getHeader(headers, 'To');
  return {
    from: extractEmailAddress(getHeader(headers, 'From')),
    to: toRaw
      ? toRaw
          .split(',')
          .map((s) => extractEmailAddress(s.trim()))
          .filter(Boolean)
      : [],
    subject: getHeader(headers, 'Subject'),
    receivedAt: message.internalDate ? new Date(Number(message.internalDate)) : new Date(),
    rfcMessageId: normalizeMessageId(getHeader(headers, 'Message-ID')),
    inReplyTo: normalizeMessageId(getHeader(headers, 'In-Reply-To')),
    references: getHeader(headers, 'References')
      .split(/\s+/)
      .map((id) => normalizeMessageId(id))
      .filter((id): id is string => Boolean(id)),
    autoGenerated: isAutoGenerated(headers),
    bulk: isBulk(headers),
  };
}

function normalizeMessageId(raw: string): string | undefined {
  const trimmed = raw.trim();
  return trimmed ? trimmed : undefined;
}

/** RFC 3834 `Auto-Submitted` (anything but `no`), plus the common vendor auto-reply markers. Pure header inspection. */
function isAutoGenerated(headers: GmailHeader[] | undefined): boolean {
  const autoSubmitted = getHeader(headers, 'Auto-Submitted').toLowerCase();
  if (autoSubmitted && autoSubmitted !== 'no') return true;
  if (getHeader(headers, 'X-Autoreply') || getHeader(headers, 'X-Autorespond') || getHeader(headers, 'X-Auto-Response-Suppress')) return true;
  const precedence = getHeader(headers, 'Precedence').toLowerCase();
  return precedence === 'auto_reply' || precedence === 'auto-reply';
}

/** Mailing-list / bulk markers: `List-Unsubscribe`, `List-Id` or `Precedence: bulk|list|junk`. */
function isBulk(headers: GmailHeader[] | undefined): boolean {
  if (getHeader(headers, 'List-Unsubscribe') || getHeader(headers, 'List-Id')) return true;
  const precedence = getHeader(headers, 'Precedence').toLowerCase();
  return precedence === 'bulk' || precedence === 'list' || precedence === 'junk';
}

/** Walks `payload`/`payload.parts` recursively (multipart messages nest a text/plain part inside multipart/alternative, etc.) and returns '' if none exists (e.g. an HTML-only message) rather than throwing — an email with no plain-text part is still a valid email to list. */
export function extractPlainTextBody(message: GmailMessage): string {
  const part = findPlainTextPart(message.payload);
  return part?.body?.data ? decodeBase64Url(part.body.data) : '';
}

export function listAttachmentRefs(message: GmailMessage): GmailAttachmentRef[] {
  return collectAttachmentParts(message.payload).map((part) => ({
    filename: part.filename as string,
    mimeType: part.mimeType ?? 'application/octet-stream',
    attachmentId: (part.body as { attachmentId: string }).attachmentId,
  }));
}
