import type { PolicyActionKey, PolicyMode } from '@orbit/shared';
import type { LLMMessage, LLMProvider } from '../llm/types';
import { decidePolicyAction, type PolicyDecision } from '../policy/policy-engine';
import type { ToolExecutionContext } from '../tools/types';
import type { ToolRegistry } from '../tools/tool-registry';

/** Resolves a tenant's currently configured mode for a policy action (DB lookup lives in apps/api). */
export type PolicyModeResolver = (
  action: PolicyActionKey,
  context: ToolExecutionContext,
) => Promise<PolicyMode>;

/**
 * Real-time progress signals emitted while a turn is running — consumed by
 * Sonde's SSE streaming endpoint (Master-Spec §33) to show the user what
 * the copilot is doing before the final text is ready. Deliberately only
 * covers what `AgentRuntime` itself directly observes (tool execution);
 * no `message.delta` token streaming — none of the three `LLMProvider`
 * implementations expose a streaming completion API today, and faking
 * token-by-token output would violate this project's "never simulate
 * functionality that does not exist" rule (docs/ASSUMPTIONS.md #267).
 */
export type AgentTurnEvent =
  | { type: 'tool.started'; toolCallId: string; toolName: string }
  | { type: 'tool.completed'; toolCallId: string; toolName: string; decision: PolicyDecision; error?: string };

export interface RunAgentTurnInput {
  systemPrompt?: string;
  messages: LLMMessage[];
  /** Guards against infinite tool-calling loops. Default 5. */
  maxToolIterations?: number;
  /** Optional progress callback — see `AgentTurnEvent`. Never awaited; a slow/throwing subscriber must not stall or break the turn. */
  onEvent?: (event: AgentTurnEvent) => void;
}

export interface ToolCallOutcome {
  toolCallId: string;
  toolName: string;
  decision: PolicyDecision;
  /**
   * The tool's actual input arguments as generated by the LLM — captured
   * unconditionally (not just for blocked calls) so a non-ALLOW outcome's
   * arguments survive to persistence (ToolInvocation.input,
   * apps/api/src/agent/agent-run-recorder.service.ts) and can later be
   * re-executed once a human approves it (FollowUpsModule,
   * docs/ORBIT_UNIFIED_EVOLUTION_CONCEPT.md §6). Previously missing
   * entirely — the reason a blocked call could never actually resume,
   * see docs/ORBIT_UNIFIED_IMPLEMENTATION_PLAN.md.
   */
  input?: Record<string, unknown>;
  output?: unknown;
  error?: string;
  /** Wall-clock time spent inside `ToolRegistry.execute()` — undefined for non-ALLOW decisions (the tool never ran). Feeds `tool_invocation_duration_seconds`, docs/ORBIT_UNIFIED_IMPLEMENTATION_PLAN.md Phase 2. */
  durationMs?: number;
}

export interface AgentTurnResult {
  finalText?: string;
  toolCallOutcomes: ToolCallOutcome[];
  iterations: number;
}

/**
 * Runs one agent turn end to end: LLMProvider -> Tool Registry -> Policy
 * Engine -> (only if ALLOWed) tool execution, looping until the LLM stops
 * requesting tools or `maxToolIterations` is hit. This is the concrete
 * implementation of the architecture principle in PRODUCT_CONTEXT.md
 * ("Agent -> Tool Registry -> Policy Engine -> Authorization Check -> Tool
 * Gateway -> Connector -> External System") — "Authorization Check" and
 * "Tool Gateway" are `resolvePolicyMode` + `ToolRegistry.execute()`.
 *
 * A SUGGEST_ONLY/REQUIRE_APPROVAL/DENY decision never calls the tool: the
 * LLM is told the outcome (via the synthetic tool-result message pushed
 * back into the conversation) but the side effect never happens here. It
 * is the caller's job (Finance/Sales workflow code, Phase 7/8) to act on a
 * REQUIRE_APPROVAL outcome by creating an Approval record.
 */
export class AgentRuntime {
  constructor(
    private readonly llm: LLMProvider,
    private readonly tools: ToolRegistry,
    private readonly resolvePolicyMode: PolicyModeResolver,
  ) {}

  async runTurn(context: ToolExecutionContext, input: RunAgentTurnInput): Promise<AgentTurnResult> {
    const maxIterations = input.maxToolIterations ?? 5;
    const messages: LLMMessage[] = [...input.messages];
    const toolCallOutcomes: ToolCallOutcome[] = [];
    let iterations = 0;

    while (iterations < maxIterations) {
      iterations += 1;

      const completion = await this.llm.complete({
        systemPrompt: input.systemPrompt,
        messages,
        tools: this.tools.toLLMToolDefinitions(),
      });

      if (completion.toolCalls.length === 0) {
        return { finalText: completion.text, toolCallOutcomes, iterations };
      }

      messages.push({ role: 'assistant', content: completion.text ?? '' });

      for (const toolCall of completion.toolCalls) {
        this.emit(input, { type: 'tool.started', toolCallId: toolCall.toolCallId, toolName: toolCall.toolName });
        const outcome = await this.executeToolCall(toolCall, context);
        this.emit(input, {
          type: 'tool.completed',
          toolCallId: outcome.toolCallId,
          toolName: outcome.toolName,
          decision: outcome.decision,
          error: outcome.error,
        });
        toolCallOutcomes.push(outcome);
        messages.push({
          role: 'user',
          content: `[tool_result:${toolCall.toolName}] ${JSON.stringify(outcome.output ?? outcome.error ?? { decision: outcome.decision })}`,
        });
      }
    }

    return { finalText: undefined, toolCallOutcomes, iterations };
  }

  private async executeToolCall(
    toolCall: { toolCallId: string; toolName: string; input: Record<string, unknown> },
    context: ToolExecutionContext,
  ): Promise<ToolCallOutcome> {
    const tool = this.tools.get(toolCall.toolName);
    if (!tool) {
      return {
        toolCallId: toolCall.toolCallId,
        toolName: toolCall.toolName,
        decision: 'DENY',
        input: toolCall.input,
        error: `Unknown tool "${toolCall.toolName}".`,
      };
    }

    const mode = await this.resolvePolicyMode(tool.policyAction, context);
    const decision = decidePolicyAction(mode);

    if (decision !== 'ALLOW') {
      return { toolCallId: toolCall.toolCallId, toolName: tool.name, decision, input: toolCall.input };
    }

    const startedAt = Date.now();
    try {
      const output = await this.tools.execute(tool.name, toolCall.input, context);
      return { toolCallId: toolCall.toolCallId, toolName: tool.name, decision, input: toolCall.input, output, durationMs: Date.now() - startedAt };
    } catch (error) {
      return {
        toolCallId: toolCall.toolCallId,
        toolName: tool.name,
        decision,
        input: toolCall.input,
        error: error instanceof Error ? error.message : String(error),
        durationMs: Date.now() - startedAt,
      };
    }
  }

  private emit(input: RunAgentTurnInput, event: AgentTurnEvent): void {
    try {
      input.onEvent?.(event);
    } catch {
      // A subscriber's own error (e.g. a broken SSE write) must never abort the turn itself.
    }
  }
}
