import type { InboundEmail } from '@orbit/integration-core';
import { GmailPollAdapter } from './gmail-poll.adapter';
import { GmailConnectorService } from '../integrations/gmail-connector.service';
import { PrismaService } from '../prisma/prisma.service';

function email(overrides: Partial<InboundEmail> = {}): InboundEmail {
  return {
    providerMessageId: 'msg-1',
    from: 'kunde@example.com',
    to: ['vertrieb@firma.example'],
    subject: 'Anfrage',
    bodyText: 'Wir haben Interesse.',
    receivedAt: new Date('2026-10-04T08:00:00Z'),
    attachments: [],
    ...overrides,
  };
}

describe('GmailPollAdapter', () => {
  function buildAdapter(emails: InboundEmail[], connectedAddress: string | null = 'konto@firma.example') {
    const gmailConnector = { listMessages: jest.fn().mockResolvedValue(emails) } as unknown as GmailConnectorService;
    const prisma = {
      forTenantId: jest.fn().mockReturnValue({
        integration: { findUnique: jest.fn().mockResolvedValue(connectedAddress ? { externalAccountId: connectedAddress } : null) },
      }),
    } as unknown as PrismaService;
    return { adapter: new GmailPollAdapter(gmailConnector, prisma), gmailConnector };
  }

  it('translates InboundEmail[] into NormalizedIntakeEvent[] with the EMAIL/gmail channel tagging, thread data and the given connectionId', async () => {
    const { adapter } = buildAdapter([
      email({ threadId: 'thread-9', rfcMessageId: '<a@x>', inReplyTo: '<b@x>', references: ['<b@x>'], autoGenerated: false, bulk: false }),
    ]);

    const result = await adapter.poll('tenant_1', 'connection_1', null);

    expect(result.events).toEqual([
      {
        tenantId: 'tenant_1',
        connectionId: 'connection_1',
        channel: 'EMAIL',
        provider: 'gmail',
        externalEventId: 'msg-1',
        occurredAt: new Date('2026-10-04T08:00:00Z'),
        sender: { address: 'kunde@example.com' },
        recipients: [{ address: 'vertrieb@firma.example' }],
        subject: 'Anfrage',
        content: 'Wir haben Interesse.',
        attachments: [],
        threadId: 'thread-9',
        rfcMessageId: '<a@x>',
        inReplyTo: '<b@x>',
        references: ['<b@x>'],
        direction: 'INBOUND',
        hints: { autoGenerated: false, bulk: false, providerSpam: false },
      },
    ]);
  });

  it('marks a message from the connected mailbox itself as OUTBOUND (derived from the Integration, never hardcoded) and a SENT-labelled one too', async () => {
    const { adapter } = buildAdapter([
      email({ providerMessageId: 'own', from: 'Konto@Firma.example' }),
      email({ providerMessageId: 'sent', from: 'someone-else@example.com', labelIds: ['SENT'] }),
      email({ providerMessageId: 'customer' }),
    ]);

    const result = await adapter.poll('tenant_1', 'connection_1', null);

    expect(result.events.map((e) => [e.externalEventId, e.direction])).toEqual([
      ['own', 'OUTBOUND'],
      ['sent', 'OUTBOUND'],
      ['customer', 'INBOUND'],
    ]);
  });

  it('passes deterministic header hints and the provider SPAM label through as hints, not as a decision', async () => {
    const { adapter } = buildAdapter([email({ autoGenerated: true, bulk: true, labelIds: ['SPAM'] })]);

    const result = await adapter.poll('tenant_1', 'connection_1', null);

    expect(result.events[0]?.hints).toEqual({ autoGenerated: true, bulk: true, providerSpam: true });
  });

  it("calls GmailConnectorService.listMessages with the given tenantId, ignoring the cursor (no incremental fetch support — see the adapter's own doc comment)", async () => {
    const { adapter, gmailConnector } = buildAdapter([]);

    await adapter.poll('tenant_2', 'connection_2', 'some-previous-cursor');

    expect(gmailConnector.listMessages).toHaveBeenCalledWith('tenant_2', expect.any(Number));
  });

  it('sets nextCursor to the most recently fetched message id, or keeps the previous cursor if nothing new was fetched', async () => {
    const { adapter: adapterWithResults } = buildAdapter([email({ providerMessageId: 'newest-msg' })]);
    expect((await adapterWithResults.poll('tenant_3', 'connection_3', 'old-cursor')).nextCursor).toBe('newest-msg');

    const { adapter: adapterEmpty } = buildAdapter([]);
    expect((await adapterEmpty.poll('tenant_3', 'connection_3', 'old-cursor')).nextCursor).toBe('old-cursor');
  });
});
